### PR TITLE
(BREAKING)Rename procedure module to orderexpansion module

### PR DESCRIPTION
**Pull request by makombe**
This PR intend to make procedure module to have a generic name since the same module is now going to be used to handle `Radiology, Procedures and Medical supply`.

Once this PR is merge I will also rename the repository to `openmrs-module-orderexpansion` 
Also, going forward we are not using `procedure omod`  but to use orderexpansion omod

### CODE REVIEW

**Review by ojwanganto — APPROVED** [review]
Thanks, @makombe. Please feel free to merge for testing

**Comment by ojwanganto** [comment]
expandedorders sounds better than orderexpansion but I think we are good to go with what you have done. Thanks for working on this

**Review by donaldkibet — APPROVED** [review]

**Comment by donaldkibet** [comment]
Should we also rename the repository name to reflect the changes make cc @makombe

**Comment by makombe** [comment]
> Should we also rename the repository name to reflect the changes make cc @makombe

Yes and I have just done that. Thanks @donaldkibet

**Pull request merged**
